name: "embedding_batch"
backend: "python"
max_batch_size: 1

input [
    {
        name: "text"
        data_type: TYPE_STRING
        dims: [-1]
    },
    {
        name: "max_length"
        data_type: TYPE_INT32
        dims: [1]
        reshape: { shape: [ ] }
        optional: true
    }
]

output [
    {
        name: "embedding"
        data_type: TYPE_FP32
        dims: [-1, 768]
    },
    {
        name: "usage"
        data_type: TYPE_STRING
        dims: [1]
    }
]

instance_group [
    {
        count: 1
        kind : KIND_GPU
        gpus: [0]
    }
]

parameters {
  key: "tokenizer_dir"
  value: {
    string_value: "/mnt/publish-data/train_data/embedding/bce-embedding-base_v1/"
  }
}
parameters {
    key: "engine_dir"
    value: {
        string_value: "/mnt/publish-data/train_data/embedding/bce-embedding-base_v1_triton_trt/RobertaModel_float16_tp1_rank0.engine"
    }
}