name: "tensorrt_llm"
backend: "python"
max_batch_size: 8

input [
    {
        name: "input_ids"
        data_type: TYPE_INT32
        dims: [-1]
    },
    {
        name: "input_lengths"
        data_type: TYPE_INT32
        dims: [-1]
    },
    {
        name: "token_type_ids"
        data_type: TYPE_INT32
        dims: [-1]
    }
]

output [
    {
        name: "embedding"
        data_type: TYPE_STRING
        dims: [-1]
    }
]

dynamic_batching {
    preferred_batch_size: [ 1, 4, 8 ],
    max_queue_delay_microseconds: 1000   # 等待时间
}

instance_group [
    {
        count: 1
        kind : KIND_GPU
        gpus: [0]
    }
]

parameters {
    key: "engine_dir"
    value: {
        string_value: "/data/caiyueliang/tensorrt-llm/examples/bert/bce-embedding-trt-llm-fp16-test/RobertaModel_float16_tp1_rank0.engine"
    }
}