name: "rerank"
backend: "python"
max_batch_size: 16

input [
    {
        name: "query"
        data_type: TYPE_STRING
        dims: [1]
        reshape: { shape: [ ] }
    },
    {
        name: "candidate"
        data_type: TYPE_STRING
        dims: [-1]
    }
]

output [
    {
        name: "score"
        data_type: TYPE_STRING
        dims: [1]
    }
]

dynamic_batching {
    preferred_batch_size: [ 8, 16 ],
    max_queue_delay_microseconds: 1000   # 等待时间
}

instance_group [
    {
        count: 1
        kind : KIND_GPU
        gpus: [0]
    }
]

parameters {
  key: "tokenizer_dir"
  value: {
    string_value: "/mnt/publish-data/train_data/rerank/bce-reranker-base_v1/"
  }
}
parameters {
    key: "engine_dir"
    value: {
        string_value: "/mnt/publish-data/train_data/rerank/bce-reranker-base_v1_triton_trt/RobertaForSequenceClassification_float16_tp1_rank0.engine"
    }
}